services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mediatis\OneTrustUtility\:
    resource: '../Classes/*'

  Mediatis\OneTrustUtility\ExpressionLanguage\TypoScriptConditionProvider:
    public: true
